package com.example.demo.domain;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table all_user
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class User implements Serializable {
    /**
     * Database Column Remarks:
     *   用户id，手机号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_user.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     * Database Column Remarks:
     *   默认和userId一样
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_user.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     * Database Column Remarks:
     *   用户头像
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_user.head_portrait
     *
     * @mbg.generated
     */
    private String headPortrait;

    /**
     * Database Column Remarks:
     *   会员等级,从0开始
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_user.vip_level
     *
     * @mbg.generated
     */
    private Integer vipLevel;

    /**
     * Database Column Remarks:
     *   用户类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_user.user_type
     *
     * @mbg.generated
     */
    private Integer userType;

    /**
     * Database Column Remarks:
     *   用户生日
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_user.birthday
     *
     * @mbg.generated
     */
    private Date birthday;

    /**
     * Database Column Remarks:
     *   用户性别
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_user.sex
     *
     * @mbg.generated
     */
    private String sex;

    /**
     * Database Column Remarks:
     *   个人简介
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_user.brief_introduction
     *
     * @mbg.generated
     */
    private String briefIntroduction;

    /**
     * Database Column Remarks:
     *   地区
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_user.area
     *
     * @mbg.generated
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table all_user
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_user.user_id
     *
     * @return the value of all_user.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_user.user_id
     *
     * @param userId the value for all_user.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_user.user_name
     *
     * @return the value of all_user.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_user.user_name
     *
     * @param userName the value for all_user.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_user.head_portrait
     *
     * @return the value of all_user.head_portrait
     *
     * @mbg.generated
     */
    public String getHeadPortrait() {
        return headPortrait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_user.head_portrait
     *
     * @param headPortrait the value for all_user.head_portrait
     *
     * @mbg.generated
     */
    public void setHeadPortrait(String headPortrait) {
        this.headPortrait = headPortrait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_user.vip_level
     *
     * @return the value of all_user.vip_level
     *
     * @mbg.generated
     */
    public Integer getVipLevel() {
        return vipLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_user.vip_level
     *
     * @param vipLevel the value for all_user.vip_level
     *
     * @mbg.generated
     */
    public void setVipLevel(Integer vipLevel) {
        this.vipLevel = vipLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_user.user_type
     *
     * @return the value of all_user.user_type
     *
     * @mbg.generated
     */
    public Integer getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_user.user_type
     *
     * @param userType the value for all_user.user_type
     *
     * @mbg.generated
     */
    public void setUserType(Integer userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_user.birthday
     *
     * @return the value of all_user.birthday
     *
     * @mbg.generated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_user.birthday
     *
     * @param birthday the value for all_user.birthday
     *
     * @mbg.generated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_user.sex
     *
     * @return the value of all_user.sex
     *
     * @mbg.generated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_user.sex
     *
     * @param sex the value for all_user.sex
     *
     * @mbg.generated
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_user.brief_introduction
     *
     * @return the value of all_user.brief_introduction
     *
     * @mbg.generated
     */
    public String getBriefIntroduction() {
        return briefIntroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_user.brief_introduction
     *
     * @param briefIntroduction the value for all_user.brief_introduction
     *
     * @mbg.generated
     */
    public void setBriefIntroduction(String briefIntroduction) {
        this.briefIntroduction = briefIntroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_user.area
     *
     * @return the value of all_user.area
     *
     * @mbg.generated
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_user.area
     *
     * @param area the value for all_user.area
     *
     * @mbg.generated
     */
    public void setArea(String area) {
        this.area = area;
    }
}