package com.example.demo.mapper;

import com.example.demo.domain.Follow;

public interface FollowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follow
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String followId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follow
     *
     * @mbg.generated
     */
    int insert(Follow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follow
     *
     * @mbg.generated
     */
    int insertSelective(Follow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follow
     *
     * @mbg.generated
     */
    Follow selectByPrimaryKey(String followId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follow
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Follow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follow
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Follow record);
}